### ISSUE TITLE
 Failed host lookup: 'accounts.google.com'

### ISSUE THREAD

**Issue by pmagnuson** [dart-lang/googleapis_auth#67]
I have written a flutter application that uses the `package:googleapis_auth/auth_io.dart`.

I have tested this with all combinations of
debug | release
Android | iOS
wifi | cellular

All combinations work except the release, Android, wifi.  on this combination I am getting the following error:

```
[  +23 ms] E/flutter (25683): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SocketException: Failed host lookup: 'accounts.google.com' (OS Error: No address associated with hostname, errno =
7)
[        ] E/flutter (25683): #0      IOClient.send (package:http/src/io_client.dart:33)
[        ] E/flutter (25683): <asynchronous suspension>
[        ] E/flutter (25683): #1      JwtFlow.run (package:googleapis_auth/src/oauth2_flows/jwt.dart:72)
[        ] E/flutter (25683): #2      clientViaServiceAccount (package:googleapis_auth/auth_io.dart:138)
[        ] E/flutter (25683): #3      _VideoLoadState.startLoading (package:yvfl/src/videoload.dart:109)
```

relavent code sections:

```dart
import 'package:googleapis/storage/v1.dart' as gcs;
import 'package:gcloud/storage.dart';
import 'package:googleapis_auth/auth_io.dart' as auth;
import 'package:connectivity/connectivity.dart';

final _credentials = new auth.ServiceAccountCredentials.fromJson({
      "type": "service_account",
      "private_key_id": "string",
      "private_key":
          "-----BEGIN PRIVATE KEY-----
            -----END PRIVATE KEY-----\n",
      "client_email": "string,
      "client_id": "string",
    });
    const _SCOPES = const [
      gcs.StorageApi.DevstorageReadOnlyScope
    ]; //read only is enough

    print('requesting remote bucket');
    try {
      auth.clientViaServiceAccount(_credentials, _SCOPES).then((client) async {
        final storage = Storage(client, 'webstorage-259216');
        final bucket = storage.bucket('bigwaveswvideo');
        //see if the file exists remotely
        ObjectInfo webInfo = await bucket.info(widget.movie);
        ...
```

The stack trace line `package:yvfl/src/videoload.dart:109)` is the source line `auth.clientViaServiceAccount(_credentials, _SCOPES).then((client) async {`.

**Comment by a-marenkov** [comment]
@pmagnuson Hi, did you solve this issue? Facing the same problem.

**Comment by pmagnuson** [comment]
For me this was an Android permission.

in AndroidManifest.xml add the line
<uses-permission android:name="android.permission.INTERNET" />

Thanks,
Phil
